apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  namespace: assignment
spec:
  containers:
  - name: single-pod-container
    image: apurwaj2/myproject
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
