apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx1
spec:
  selector:
    app: nginx1
  type: NodePort
  ports:
  - nodePort: 31001
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx1
  serviceName: "nginx-service"
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx-pod-web
        image: apurwaj2/staticwebserver
        ports:
        - containerPort: 80
